workspace:
  base: /go
  path: src/github.com/msuterski/drone-google-cloudstorage

pipeline:
  build:
    image: golang:1.9
    environment:
      - CGO_ENABLED=0
    commands:
      - make deps
      - make vet
      - make test
      - make build

  docker:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: msuterski/drone-gcs
    tag: latest
    when:
      branch: master

  docker:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: msuterski/drone-gcs
    tag: develop
    when:
      event: push
